version: '3'

services:

  db:
    image: 'postgres'
    ports:
      - "5437:5432"
    container_name: grammar-rush-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres